### ISSUE TITLE
[8.9 QA] Validate connector clients

### ISSUE THREAD

**Issue by DianaJourdan** [elastic/connectors#1146]
## Non-regression QA

_**This ticket should cover the validation of the following connectors:**_

```[tasklist]
### Tasks
- [ ] Network Drive
- [ ] S3
- [ ] Azure Blob Storage
- [ ] GCS
- [ ] GDB (Postgress, oracle, MS-SQL)
- [ ] Confluence (Online & Server)
- [ ] Jira (Online & Server)
- [ ] Sharepoint Server
```

**Note:** always test with the latest Build Candidate on Elastic Cloud, using the full Elastic stack

- [ ] Start the whole stack from scratch and navigate to Enterprise Search
- [ ] Check that no indices are shown in the top level Indices list
- [ ] Click on "Create an Elasticsearch index" - a new page is open where you can select an ingestion method
- [ ] Choose Connector -> Use a connector
- [ ] Choose the connector you want to test and Continue
- [ ] Create an index with a valid name and Universal language
-------

- [ ] Connector name and description are editable on the Configurations page
- [ ] Connector can be deleted from the Indices page
- [ ] Connector can be deleted from the Indices page and it can be recreated with the same name after
- [ ] Pull connectors repository, run `make install` but do not run connector yet

- [ ] Verify that you are redirected to "configuration" page where you can create an api key and can copy connector id / whole section of config into the connector
- [ ] Update connector configuration with the api_key and connector_id, plus choose a service_type to test and set it in config
- [ ] Start the connector by running `make run` - verify that it starts and does not actually do anything yet
- [ ] Wait for the Kibana page with the connector configuration to update and verify that it's possible to edit connector configuration now
- [ ] Edit and save connector configuration, then reload the page and verify that configuration is properly saved
- [ ] Click on "Set schedule and sync" and verify that you're redirected to the scheduling tab
- [ ] Enable scheduling for frequency = every minute and save schedule; refresh the page and verify that the changes were stored
- [ ] Switch to the connector and wait for a minute or two, verify that connector starts to ingest data
- [ ] Verify that the data from the connector appears in the expected index
- [ ] Verify that on the index list page index information is updated properly, showing expected number of documents and new index size
- [ ] Verify that on the connector overview page "Document Count" is updated to reflect the number of documents in the index
- [ ] Verify that you can see ingested documents in `documents` tab
- [ ] Verify that index mappings are correct on the `index mappings` tab

**Record a short demo showing the connectors' configuration and that there were documents ingested**

**Comment by khushbu-elastic** [comment]
@DianaJourdan  @danajuratoni 

We have validated the following connectors and recorded the demo for them & uploaded on drive:

1. Jira - [Jira Server](https://drive.google.com/file/d/16mmMIn3zMDJkV0XHhn_JedVnWVXmrHLB/view?usp=drive_link) & [Jira Cloud](https://drive.google.com/file/d/1TvTkpYb-PxN8kjxx4y7RHEvUES9FLuKj/view?usp=drive_link)
2. Confluence - [Confluence Server](https://drive.google.com/file/d/1S6ZND3PsxsslwitHNGQs_S7Fbx3S1ezF/view?usp=drive_link) & [Confluence Cloud](https://drive.google.com/file/d/1E_q0nC6vM_ty4xgUKAwPRGD_vqK0wirn/view?usp=drive_link)
3. [Amazon S3](https://drive.google.com/file/d/1Kj1-9uLY78YmhFeDfOzpClkrC1TLaw8t/view?usp=drive_link)
4. [Azure Blob Storage](https://drive.google.com/file/d/1-f2usyMku5ph1gBiXZ6nlcIV6McSoA1l/view?usp=drive_link)

We will keep here updating for other connectors, as and when done

NOTE: 

1. For --> Enable scheduling for frequency = every minute and save schedule; refresh the page and verify that the changes were stored --> Setting the Scheduling with frequency= every minute is not possible as UI doesn't provide the option to set schedule every minute.
6. For --> Verify that on the index list page index information is updated properly, showing the expected number of documents and new index size --> The Index size is not displayed on the Elasticsearch Indices page. We are able to check the same from Index Management Page as it is displayed there.

Also, please take a note that we are still unable to create the Index for GCS -[ github issue](https://github.com/elastic/connectors-python/issues/1168)

**Comment by khushbu-elastic** [comment]
@DianaJourdan @danajuratoni

We have validated the sharepoint_server connector and recorded the demo for it & uploaded on drive:

Sharepoint- [Sharepoint Server](https://drive.google.com/file/d/1DhWZhDWbsJOjMYp5hX_tIRrg6g-CjyCk/view?usp=drive_link)

**Comment by khushbu-elastic** [comment]
@DianaJourdan @danajuratoni

We have validated the GDB (MS-SQL) connector and recorded the demo for it & uploaded on drive:

[MS-SQL](https://drive.google.com/file/d/1vHm5JQLdOvLvd0nT15UTYpeIid_AOLI6/view?usp=drive_link)

**Comment by khushbu-elastic** [comment]
@DianaJourdan @danajuratoni 
We have validated the Network Drive connector & recorded the demo for it which is uploaded on the google drive.

[Network Drive ](https://drive.google.com/file/d/1BIUQ3XZBIvCRGSuioo5tvvrGRW0acMVG/view?usp=drive_link)

Could you please mark the checklist items in the Task as Done for the connectors for which the checklist has been performed & demo is shared, after verifying it from your end once?

**Comment by khushbu-elastic** [comment]
@DianaJourdan @danajuratoni In the latest release of 8.9.1, GCS is not available to check as a Native Connector. 
So could we close this issue considering GCS would be a part of future release and create a separate issue for GCS whenever required?
