### ISSUE TITLE
Improve code structure for Jira and Confluence

### ISSUE THREAD

**Issue by moxarth-elastic** [elastic/connectors#1417]
### Problem Description
Update code structure for Jira and Confluence connectors with moving some methods to client class.

```[tasklist]
### Tasks
- [ ] move methods to client class for Jira connector
- [ ] move methods to client class for Confluence connector
- [ ] https://github.com/elastic/connectors-python/issues/1512
- [ ] https://github.com/elastic/connectors-python/issues/1559
```

**Comment by timgrein** [comment]
Looks good, thanks for tracking it.

**Comment by danajuratoni** [comment]
@moxarth-elastic when is it expected to get the last couple of tasks fixed? cc: @DianaJourdan

**Comment by moxarth-elastic** [comment]
@danajuratoni we can start working on this and expect the PR in the next week.
