### ISSUE TITLE
DLS: Network Drive, OneDrive

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors#1592]
Enhance the 2 mentioned connectors with document level security.

### Acceptance criteria
- [x] Discovery document with DLS for Network Drive, OneDrive
- [x] #1634
- [x] #1628
- [x] Functional tests performed
- [x] #1633
   - with several examples illustrating the syntax, how a basic use case works, limitations
- [x] #1632
   - with several examples illustrating the syntax, how a basic use case works, limitations
- [x] Performance test/ reports against the last stable release branch of the connector framework and in Elastic Cloud
- [ ] Updated docs

**Comment by abhishekjoshi-crest** [comment]
Updates - [7th September - 14th September]:

- Work on OneDrive DLS implementation
- PR #1635 raised for the same
- Addressed suggested nits
- Waiting for re-review

**Comment by abhishekjoshi-crest** [comment]
Updates - [15th September - 21st September]:

- Implementation & docs for OneDrive DLS  #1635 got merged
- Performance testing going on

**Comment by praveen-elastic** [comment]
Updates - [20th September - 27th September]

- Worked on implementation of DLS in Network Drive
- Functional Testing is in progress for NAS DLS, will raise a PR soon

**Comment by khushbu-elastic** [comment]
@danajuratoni  @danajuratoni  Functional tests performed --> Done for Onedrive & Network drive Connectors.

**Comment by khushbu-elastic** [comment]
@danajuratoni Hereby, sharing the Performance testing document for Network drive DLS (Windows) - https://docs.google.com/document/d/1NHOBHDYG9HqQHMdaCU0OeS2QykkLOWApr_pRvx33puI/edit?usp=sharing

Please review the same & let us know your feedback, if any.

Performance test/ reports against the last stable release branch of the connector framework and in Elastic Cloud --> **Done**
 Updated docs --> **Done**

As the above points are done, can we mark them as done and close this issue?

**Note**: We are separately tracking the issue for Linux Network Drive DLS as an enhancement here - https://github.com/elastic/connectors/issues/1774

**Comment by danajuratoni** [comment]
Thanks for sharing the Network Drive performance report, looks good!
Could you share the link for the OneDrive performance report too?
Thanks!

**Comment by khushbu-elastic** [comment]
@danajuratoni Here is the [performance document](https://docs.google.com/document/d/1AmCuccM4GJ_re6iXv3mxCGHhmIjvEMFzt1MGdXjqm3U/edit#heading=h.5lko809bi3bd) for OneDrive connector.

**Comment by khushbu-elastic** [comment]
@danajuratoni For OneDrive DLS Performance testing, there is a performance issue same as we have for Jira, and we discussed it in the sync up call.
And therefore, we have added a limitation for onedrive in the discovery document - https://docs.google.com/document/d/1H8fgQ7OoHHhYYCM6dOgtIiF5BPYjNxOoMZnHKne8n3M/edit

Please let us know your opinion if we want to track it separately, like Jira.

**Comment by danajuratoni** [comment]
@leemthompo let's make sure the documentation mentions this performance degradation similar to how we documented it for Jira. Thanks!

Closing this issue as done.
