### ISSUE TITLE
DLS: ServiceNow, Dropbox

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors#1819]
Enhance the 2 mentioned connectors with document level security.

### Acceptance criteria
- [x] Discovery document with DLS for  ServiceNow, Dropbox
- [x] Add DLS support for ServiceNow as defined in the discovery
- [x] Add DLS support for Dropbox as defined in the discovery
- [x] Functional tests performed
- [x] DLS documentation for ServiceNow
   - with several examples illustrating the syntax, how a basic use case works, limitations
- [x] DLS documentation for Dropbox
   - with several examples illustrating the syntax, how a basic use case works, limitations
- [x] Performance test/ reports against the last stable release branch of the connector framework and in Elastic Cloud
- [x] Updated docs

**Comment by abhishekjoshi-crest** [comment]
Progress summary [19th Oct - 26th Oct]:

ServiceNow
- Shared Discovery Document
- Start Implementation of ServiceNow DLS

**Comment by seanstory** [comment]
Document link: https://docs.google.com/document/d/1sxiiX-WuopQxDhyXEeLThhkDYPdqp1Lku45iGfK_d9g/edit

**Comment by akanshi-elastic** [comment]
Progress summary [19th Oct - 26th Oct]:

Dropbox

Shared Discovery Document
Start Implementation of Dropbox DLS

**Comment by akanshi-elastic** [comment]
Progress summary [26th Oct - 2nd Nov]:

Dropbox
Raised Dropbox DLS PR on github
Address comments for dropbox DLS PR

**Comment by akanshi-elastic** [comment]
Progress summary [3rd Nov - 9th Nov]:

Dropbox
Address comments for dropbox DLS PR

**Comment by akanshi-elastic** [comment]
Progress summary [13th Nov - 15th Nov]:

Dropbox
PR merged for Dropbox DLS in main

**Comment by akanshi-elastic** [comment]
Progress summary [17th Nove-22Nov]:
Dropbox
PR for DLS documentation got merged

**Comment by parthpuri-elastic** [comment]
Weekly status update [2 Nov 2023 to 9 Nov 2023]

- raised draft PR for Servicenow DLS
- Discussion is ongoing with Nav and Sean

Weekly status update [9 Nov 2023 to 16 Nov 2023]

- Raised the issue of extra roles in discussion forum

**Comment by parthpuri-elastic** [comment]
Weekly status update [24 Nov 2023 to 30 Nov 2023]

- We are able to fetch content from the user who has extra permission, so will check more after MongoDB

**Comment by parthpuri-elastic** [comment]
Weekly status update [8 Dec 2023 to 14 Dec 2023]

- Internal testing is on-going

**Comment by parthpuri-elastic** [comment]
Weekly status update [15 Dec 2023 to 21 Dec 2023]

- Raised PR #1989 for ServiceNow DLS and addressing comments

**Comment by parthpuri-elastic** [comment]
Weekly status update [22 Dec 2023 to 4 Jan 2024]

- PR https://github.com/elastic/connectors/pull/1989 Merged for ServiceNow DLS
- Performance Testing completed
- Raised Documentation [PR](https://github.com/elastic/connectors/pull/2025)

**Comment by navarone-feekery** [comment]
(For future reference's sake)
Dropbox DLS discovery doc: https://docs.google.com/document/d/1zMNZ3SskqdtoFNPmaudjxK-AiBoacPX84mGWFUpn42w/edit
