### ISSUE TITLE
[Connectors][Docker] Make release docker images available in docker hub

### ISSUE THREAD

**Issue by jedrazb** [elastic/connectors#1844]
### Problem Description

Elastic connectors image doesn’t show up in registries:
We don’t have an official image listed in the [Docker Hub](https://hub.docker.com/search?q=elastic+connectors) registry 
We are not present in [docker.elastic.co](https://www.docker.elastic.co/) registry search on the public, user-facing website

### Proposed Solution

Check how to submit our connectors docker image to the docker hub registry

### Tasks

- [ ] Research and document how to properly publish docker images for public access (connectors and content-extraction service are not visible on docker.elastic.co)
- [ ] Share the steps with ent-search folks
- [x] Put connectors docker image into docker.elastic.co

**Comment by jedrazb** [comment]
Related to: https://github.com/elastic/data-extraction-service/issues/23

It would be good to capture the steps to properly release docker image in an ent-search wiki?

**Comment by ppf2** [comment]
A few things that are confusing today and would be nice to address as part of this effort:

1.  We don't have Docker images for all matching Elasticsearch versions down to the maintenance level.
2. For the images we shared, we appear to only have the latest tagged version as Docker images, not the full set.  For instance, 8.1.0.0 is missing and can't be pulled ...

<img width="326" alt="image" src="https://github.com/elastic/connectors/assets/7216393/bd98776d-1c46-418a-b5e5-47a7e1fc3133">

**Comment by predogma** [comment]
The seems to be only two images available at this time
```
docker pull docker.elastic.co/enterprise-search/elastic-connectors:8.10.2.0
docker pull docker.elastic.co/enterprise-search/elastic-connectors:8.9.2.0
```
Any other version tag listed in the project here result in manifest unknown
```
% docker pull docker.elastic.co/enterprise-search/elastic-connectors:8.10.0.0
% docker pull docker.elastic.co/enterprise-search/elastic-connectors:8.9.0.0
% docker pull docker.elastic.co/enterprise-search/elastic-connectors:8.6.02

Error response from daemon: manifest for docker.elastic.co/enterprise-search/elastic-connectors:8.10.0.0 not found: manifest unknown: manifest unknown
```

I do not see this documented in project.  There is also no latest tag either.  Is this bug

**Comment by seanstory** [comment]
infra issue to address making the docker images public/searchable: https://github.com/elastic/infra/issues/40122

**Comment by jedrazb** [comment]
We already "sort of" expose connector docker images: https://www.docker.elastic.co/r/enterprise-search/elastic-connectors ... but you have to know the exact link to find it

**Comment by jedrazb** [comment]
Adding this to our DOCKER.md https://github.com/elastic/connectors/pull/1866

**Comment by jedrazb** [comment]
The image is available in docker.elastic.co 🥳 Thank you @seanstory
