### ISSUE TITLE
[8.11 QA] Validate connector client

### ISSUE THREAD

**Issue by khushbu-elastic** [elastic/connectors#1846]
## Non-regression QA

```[tasklist]
### Tasks
- [x] Zoom
- [x] Outlook
- [x] Microsoft Teams
- [x] Box
- [x] Onedrive
- [x] Dropbox
- [x] Github
- [x] Servicenow
```
**Note:** always test with the latest Build Candidate on Elastic Cloud, using the full Elastic stack

- [x] Start the whole stack from scratch and navigate to Enterprise Search
- [x] Check that no indices are shown in the top level Indices list
- [x] Click on "Create an Elasticsearch index" - a new page is open where you can select an ingestion method
- [x] Choose Connector -> Use a connector
- [x] Choose the connector you want to test and Continue
- [x] Create an index with a valid name and Universal language
-------

- [x] Connector name and description are editable on the Configurations page
- [x] Connector can be deleted from the Indices page
- [x] Connector can be deleted from the Indices page and it can be recreated with the same name after
- [x] Pull connectors repository, run `make install` but do not run connector yet

- [x] Verify that you are redirected to "configuration" page where you can create an api key and can copy connector id / whole section of config into the connector
- [x] Update connector configuration with the api_key and connector_id, plus choose a service_type to test and set it in config
- [x] Start the connector by running `make run` - verify that it starts and does not actually do anything yet
- [x] Wait for the Kibana page with the connector configuration to update and verify that it's possible to edit connector configuration now
- [x] Edit and save connector configuration, then reload the page and verify that configuration is properly saved
- [x] Click on "Set schedule and sync" and verify that you're redirected to the scheduling tab
- [ ] Enable scheduling for frequency = every minute and save schedule; refresh the page and verify that the changes were stored
- [x] Switch to the connector and wait for a minute or two, verify that connector starts to ingest data
- [x] Verify that the data from the connector appears in the expected index
- [x] Verify that on the index list page index information is updated properly, showing expected number of documents and new index size
- [x] Verify that on the connector overview page "Document Count" is updated to reflect the number of documents in the index
- [x] Verify that you can see ingested documents in `documents` tab
- [ ] Verify that index mappings are correct on the `index mappings` tab

**Record a short demo showing the connectors' configuration and that there were documents ingested**

**Comment by khushbu-elastic** [comment]
@DianaJourdan @danajuratoni

We have validated the following connectors and recorded the demo for them & uploaded on drive:

[Zoom](https://drive.google.com/file/d/1oux-Xtr1myESiryEPZ0sVK_yQi3-i__c/view?usp=drive_link)
[OneDrive](https://drive.google.com/file/d/1dlPSmCylRKOae-UPWuGxJq7yYSQ2AugF/view?usp=drive_link)
[Github](https://drive.google.com/file/d/1od8_9a-5SRc_DBEz4P_l9nItQXoaHkNi/view?usp=drive_link) 
[Servicenow](https://drive.google.com/file/d/13UpVpBgkyLpM979jsCZ-d6QZXgXK1A2q/view?usp=drive_link)

We will keep here updating for other connectors, as and when done

NOTE:

For --> Enable scheduling for frequency = every minute and save schedule; refresh the page and verify that the changes were stored --> Setting the Scheduling with frequency= every minute is not possible as UI doesn't provide the option to set schedule every minute.
For --> Verify that on the index list page index information is updated properly, showing the expected number of documents and new index size --> The Index size is not displayed on the Elasticsearch Indices page. We are able to check the same from Index Management Page as it is displayed there.

**Comment by khushbu-elastic** [comment]
@danajuratoni @DianaJourdan We have performed the QA Checklist for the above mentioned connectors and recorded a short demo showing the connectors' configuration and that there were documents ingested.

Please check the same from your end once and update here so that we can mark this issue as Completed, after your confirmation.

**Comment by khushbu-elastic** [comment]
@danajuratoni  @DianaJourdan Please check this once and share your feedback, if any, in order to update the task status.
