### ISSUE TITLE
Redis connector client (8.13 Tech Preview)

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors#1941]
## New Redis connector
New connector client to be released with 8.13 in Beta.
Preliminary date for **8.13 Feature Freeze**:  Tue, Feb 06 2024

### Acceptance criteria
- [x] TDD in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] QA plan in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] Advanced Sync rules using Redis queries
- [x] Code merged in main following the defined PR process
- [x] Functional tests performed
- [ ] DEFERRED ~Performance test/ reports against the last stable release branch of the connector framework and in Elastic Cloud~
     - ~Performance Stats Report in [GDrive](https://docs.google.com/document/d/1mYxwCliFTmG0M-CUJjxsfLzr0Pf5-Pb_/edit?usp=sharing&ouid=101132896583575395288&rtpof=true&sd=true)~
- [x] Connector client documentation in repo 
- [x] Demo of the connector in latest builds in Elastic Cloud in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x]  Ingestion engineer added a comment to this ticket to sign off for Redis
     - [x] Code backported to the correct version 
     - [x] Automated tests to 90% coverage
- [x] Regression test suite performed for the release along with QA day for all supported OS in https://www.elastic.co/support/matrix

**Comment by akanshi-elastic** [comment]
Progress Summary
1. Start analysis for Redis
2. Start preparing TDD(including sync rules) for Redis connector

**Comment by akanshi-elastic** [comment]
Progress Summary[21stdec-26dec]

1.Shared TDD(including sync rules) for Redis connector
2. Start working on ping+indexing  for Redis

**Comment by akanshi-elastic** [comment]
Progress Summary[28st dec-3rd jan]
1. Start working on ping+indexing  for Redis
2. Start working on sync rules for redis

**Comment by akanshi-elastic** [comment]
Progress Summary[11th dec-18th jan]
 1. Raised ping+indexing PR for Redis
 2. Start Address comments for same PR

**Comment by kajal-elastic** [comment]
@danajuratoni Regression testing is completed for Redis connector as we are doing for other connectors on Ubuntu, Alma Linux 8, Rocky Linux 8, CENT OS

**Comment by wangch079** [comment]
Signed off the connector:
1. Confirmed code is backported to 8.13
2. Confirmed the test coverage is above 90%

**Comment by danajuratoni** [comment]
Closing as done
