### ISSUE TITLE
Notion connector client (8.13 Beta)

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors#1958]
## New Notion connector
New connector client to be released with 8.13 in Beta.
Preliminary date for **8.13 Feature Freeze**:  Tue, Feb 06 2024

### Acceptance criteria
- [x] TDD in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] QA plan in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] Advanced Sync rules
- [x] Code merged in main following the defined PR process
- [x] Functional tests performed
- [x] Performance test/ reports against the last stable release branch of the connector framework and in Elastic Cloud 
     - Performance Stats Report in [GDrive](https://docs.google.com/document/d/1mYxwCliFTmG0M-CUJjxsfLzr0Pf5-Pb_/edit?usp=sharing&ouid=101132896583575395288&rtpof=true&sd=true)
- [x] Connector client documentation in repo 
- [x] Demo of the connector in latest builds in Elastic Cloud in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x]  Ingestion engineer added a comment to this ticket to sign off
     - [x] Code backported to the correct version 
     - [x] Automated tests to 90% coverage
- [x] Regression test suite performed for the release along with QA day for all supported OS in https://www.elastic.co/support/matrix 
- [x] Compatibility tests for running connector as native in Cloud

**Comment by praveen-elastic** [comment]
Progress Summary:

- Started analysis of Notion as a Source.
- Prepared the Design Document and shared it with the Team.

**Comment by praveen-elastic** [comment]
Progress Summary:
- Addressed Comments in the TDD 
- Started Ping, Configuration validation and Indexing implementation.

**Comment by praveen-elastic** [comment]
Progress Summary:
- Raised a PR for indexing functionality

**Comment by praveen-elastic** [comment]
Progress Summary:
- Resolved comments for indexing functionality and the PR is merged.
- Started working on E2E.

**Comment by praveen-elastic** [comment]
Mistakenly closed due to merging of PR

**Comment by praveen-elastic** [comment]
Progress Summary: 
- PR for advanced sync rules got merged. 
- Captured Performance Stats and shared in slack. Drive link: https://docs.google.com/document/d/1tfNcETjuEmsxBzgZYTXZMBBJxs6AG84j0110GsagUrY/edit?pli=1
- Implemented retry for paginated calls.

**Comment by praveen-elastic** [comment]
Hey, @seanstory we need your comment to sign-off this connector so that we can ask @danajuratoni close this issue 🙂.

**Comment by seanstory** [comment]
Sign off granted. The connector is in 8.13, with improvements coming in 8.14. Test coverage is sufficient, and the implementation matches the TDD.

One piece that's missing still is official docs for Advanced Sync Rules (they're still in MD), but Liam is on it.

**Comment by danajuratoni** [comment]
Docs are covered in a separate ticket, closing this as done.
