### ISSUE TITLE
[8.12 QA] Validate connector client

### ISSUE THREAD

**Issue by kajal-elastic** [elastic/connectors#1987]
## Non-regression QA

**This ticket should cover the validation of the following connectors:**

```[tasklist]
### Tasks
- [ ] Dropbox
- [ ] Github
- [ ] S3
- [ ] Servicenow
- [ ] OneDrive
- [ ] GCS
- [ ] Network Drive
- [ ] Microsoft Teams
- [ ] Salesforce
```
**The above connectors will be verified as Connector Client**

**Note:** always test with the latest Build Candidate on Elastic Cloud, using the full Elastic stack

- [x] Start the whole stack from scratch and navigate to Enterprise Search
- [x] Check that no indices are shown in the top level Indices list
- [x] Click on "Create an Elasticsearch index" - a new page is open where you can select an ingestion method
- [x] Choose Connector -> Use a connector
- [x] Choose the connector you want to test and Continue
- [x] Create an index with a valid name and Universal language
-------

- [x] Connector name and description are editable on the Configurations page
- [x] Connector can be deleted from the Indices page
- [x] Connector can be deleted from the Indices page and it can be recreated with the same name after
- [x] Pull connectors repository, run `make install` but do not run connector yet

- [x] Verify that you are redirected to "configuration" page where you can create an api key and can copy connector id / whole section of config into the connector
- [x] Update connector configuration with the api_key and connector_id, plus choose a service_type to test and set it in config
- [x] Start the connector by running `make run` - verify that it starts and does not actually do anything yet
- [x] Wait for the Kibana page with the connector configuration to update and verify that it's possible to edit connector configuration now
- [x] Edit and save connector configuration, then reload the page and verify that configuration is properly saved
- [x] Click on "Set schedule and sync" and verify that you're redirected to the scheduling tab
- [ ] Enable scheduling for frequency = every minute and save schedule; refresh the page and verify that the changes were stored
- [x] Switch to the connector and wait for a minute or two, verify that connector starts to ingest data
- [x] Verify that the data from the connector appears in the expected index
- [x] Verify that on the index list page index information is updated properly, showing expected number of documents and new index size
- [x] Verify that on the connector overview page "Document Count" is updated to reflect the number of documents in the index
- [x] Verify that you can see ingested documents in `documents` tab
- [x] Verify that index mappings are correct on the `index mappings` tab

**Record a short demo showing the connectors' configuration and that there were documents ingested**

**Comment by khushbu-elastic** [comment]
@danajuratoni @DianaJourdan As you mentioned in slack, we have created this issue for validating connector client in 8.12. Please review this and let us know your feedback, if any for this ticket.

**Comment by DianaJourdan** [comment]
@khushbu-elastic thanks, it looks ok. Please move further with the testing

**Comment by kajal-elastic** [comment]
@DianaJourdan @danajuratoni In Elastic Deployment 8.12.0 , Few of the connectors available as native which are not getting executed

The connectors listed below are Stuck in **Waiting for Sync** state, despite the configuration parameters being correct

- S3
- Google Cloud Storage
- Salesforce

So we are unable to verify the QA Checklist for these connectors.

**Comment by khushbu-elastic** [comment]
@DianaJourdan @danajuratoni

We have validated the following connectors and recorded the demo for them & uploaded on drive:

[Dropbox](https://drive.google.com/file/d/1qcId14eYrNAqHNDR41CE1sW6WwWPS_wj/view?usp=drive_link)
[GitHub](https://drive.google.com/file/d/1Cb4YtYLEzNTAYsXb3THPWLONEcFAdCPD/view?usp=drive_link)
[ServiceNow](https://drive.google.com/file/d/14jHo9EjY6mma4nF-eBXkwzyFjaSwjgbF/view?usp=drive_link)
[Onedrive](https://drive.google.com/file/d/1_9DI5gTRb7ESiGO4kS6pRgwMCsiyf55Y/view?usp=drive_link)

We will keep here updating for other connectors, as and when done

NOTE:
1. For other connectors, as @kajal-elastic has mentioned, they are not getting executed and remains in Waiting for Sync state, despite the configuration parameters value being correct. We are unable to verify the QA Checklist for those connectors. Please provide with a solution for them.
2. For --> Enable scheduling for frequency = every minute and save schedule; refresh the page and verify that the changes were stored --> Setting the Scheduling with frequency= every 5 minutes is there so we have checked it for specific minute in every hour..
3. For --> Verify that on the index list page index information is updated properly, showing the expected number of documents and new index size --> The Index size is not displayed on the Elasticsearch Indices page. We are able to check the same from Index Management Page as it is displayed there.

**Comment by khushbu-elastic** [comment]
@DianaJourdan  @danajuratoni We have added the demos for the connectors mentioned in the tickets. Please refer the above comments and review the demos.
However, we are still stuck for the connectors mentioned by @kajal-elastic in the above comment. Please check them too and provide with the solution so that we can move further with this ticket.

**Comment by kajal-elastic** [comment]
@DianaJourdan @danajuratoni 
We have validated the following connectors and recorded the demo for them & uploaded on drive: 

[S3](https://drive.google.com/file/d/1cflesg1pnX5DHsTMs7GCq7F8e2NPpqq2/view?usp=drive_link)
[Google Cloud Storage](https://drive.google.com/file/d/1Ma4P8AlzF_1ZR2Kuoo6kjpWW2O0j92zT/view?usp=drive_link)
[Salesforce](https://drive.google.com/file/d/1Y5-oysx2kkkngflooBgougWDqx2vPGQM/view?usp=drive_link)

Please verify the same from your end once and update here so that this task can be marked as Completed

**Comment by khushbu-elastic** [comment]
@DianaJourdan @danajuratoni  Please check this and update the status for this ticket
