### ISSUE TITLE
GraphQL connector client (8.14 Tech Preview)

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors#2068]
## New GraphQL connector
New connector client to be released with 8.14 in Tech Preview.
[Project Brief](https://docs.google.com/document/d/1zmzfhfJ9uJCCf8-uK2n4Wl2NXyLDDZwxIw5BLceo_rQ/edit)
Preliminary date for **8.14 Feature Freeze**:  Apr 2024

### Acceptance criteria
- [x] TDD in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] QA plan in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] Code merged in main following the defined PR process
- [x] Functional tests performed
- [x] Connector client documentation in repo, elastic.co docs
- [x] Demo of the connector in latest builds in Elastic Cloud in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x]  Ingestion engineer added a comment to this ticket to sign off
     - [x] Code backported to the correct version 
     - [x] Automated tests to 90% coverage
- [x] Regression test suite performed for the release along with QA day for all supported OS in https://www.elastic.co/support/matrix 
- [x] Compatibility tests for running connector as native in Cloud

**Comment by parthpuri-elastic** [comment]
**Progress Summary** [11th Jan-18th Jan]

- Shared TDD for GraphQL Connector
- Start working on implementation

**Comment by parthpuri-elastic** [comment]
Progress Summary [25th Jan-01th Jan]

- Resolved TDD comments
- Implementation is on-going

**Comment by parthpuri-elastic** [comment]
Progress Summary [2nd Feb - 8th Feb ]

- Resolved TDD comments
- Raised PR for Ping & Indexing (https://github.com/elastic/connectors/pull/2134)

**Comment by parthpuri-elastic** [comment]
Progress Summary [9th Feb - 15th Feb]

- Resolved PR comments
- Updating the code as per latest TDD comments

**Comment by parthpuri-elastic** [comment]
Progress Summary [16th Feb - 22nd Feb]

- Started working on E2E
- Exploring GrapgQL pagination

**Comment by parthpuri-elastic** [comment]
Progress Summary [29th Feb - 07th March]

- Add pagination as discussed and addressed comments on [PR](https://github.com/elastic/connectors/pull/2134).
- Will raise PR for E2E once Indexing PR got merged.

**Comment by kajal-elastic** [comment]
@danajuratoni Demo of GraphQL connector on latest build in Elastic Cloud is uploaded on [GDrive](https://drive.google.com/file/d/1zDBaCUdPtxubOLIVIJ7j9KUWvW4arLIi/view?usp=sharing)

**Comment by kajal-elastic** [comment]
@danajuratoni @DianaJourdan For this task in To-do list - 

- [ ] Regression test suite performed for the release along with QA day for all supported OS in https://www.elastic.co/support/matrix - **Regression testing is already done on the latest code.** 

Please let us know when the 8.14 QA Day issue will be available. So, that we can verify GraphQL connector in the same and close this issue.

**Comment by kajal-elastic** [comment]
Regression Testing is completed for GraphQL connector in 8.14.0 Elastic Deployment.

**Comment by jedrazb** [comment]
✅ Confirming that:
- Code backported to the correct version
- Automated tests to 90% coverage

**Comment by danajuratoni** [comment]
Closing as done.
