### ISSUE TITLE
Add auto-generated changelogs

### ISSUE THREAD

**Issue by navarone-feekery** [elastic/connectors#2154]
### Problem Description

The connector versioning is different from the main Elasticsearch stack, as we have releases that go down to the patch level.

Elasticsearch: `major.minor.maintenance` e.g. `v8.12.0`
Connectors: `major.minor.maintenance.patch` e.g. `v8.12.0.1`

Maintenance-level releases have release notes that are covered by the Elasticsearch release cycle, but patch-level release notes don't exist. This can cause issues when trying to determine what changed between patch releases for connector clients.

These release notes should be auto-generated, possibly based on a release-note label. This is how it's done in the Elasticsearch repo. GitHub also has some support for auto-generated release notes we could look into.

```[tasklist]
### Tasks
- [ ] Investigate auto-generated release note possibilities
- [ ] (TODO: add steps here based on investigation)
- [ ] Update PR guidelines
```
