### ISSUE TITLE
OpenText Documentum connector client (8.14 Preview)

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors#2163]
## New OpenText Documentum connector
New connector client to be released with 8.14 in Preview.
Preliminary date for **8.14 Feature Freeze**:  Apr 16, 2024

### Acceptance criteria
- [x] TDD in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] QA plan in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [ ] N/A ~Advanced Sync rules~
- [ ] N/A ~DLS~
- [x] Code merged in main following the defined PR process
- [ ] N/A~Functional tests performed~
- [ ] N/A ~Performance test/ reports against the last stable release branch of the connector framework and in Elastic Cloud~ 
(https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] Connector client documentation in repo 
- [ ] ~Demo of the connector in latest builds in Elastic Cloud in [GDrive]~(https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x]  Ingestion engineer added a comment to this ticket to sign off
     - [ ] Code backported to the correct version 
     - [x] Automated tests to 90% coverage
- [ ] Regression test suite performed for the release along with QA day for all supported OS in https://www.elastic.co/support/matrix

**Comment by danajuratoni** [comment]
@moxarth-elastic I can't seem to find the connector client documentation. Is there a PR for this?

**Comment by moxarth-elastic** [comment]
@danajuratoni we've prepared the connector client doc and raised a PR for the same: https://github.com/elastic/connectors/pull/2416

**Comment by moxarth-elastic** [comment]
@danajuratoni connector client[ documentation PR](https://github.com/elastic/connectors/pull/2416) is merged.

**Comment by danajuratoni** [comment]
Closing as done
