### ISSUE TITLE
DLS: SharePoint Server, Outlook

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors#2405]
Enhance the 2 mentioned connectors with document level security.

### Acceptance criteria
- [x] Discovery document with DLS for SharePoint Server and Outlook
- [x] Add DLS support for SharePoint Server as defined in the discovery
- [x] Add DLS support for Outlook as defined in the discovery
- [ ] Functional tests performed
- [x] DLS documentation for SharePoint Server
   - with several examples illustrating the syntax, how a basic use case works, limitations
- [x] DLS documentation for Outlook
   - with several examples illustrating the syntax, how a basic use case works, limitations
- [x] Performance test/ reports against the last stable release branch of the connector framework and in Elastic Cloud
- [x] Updated docs

**Comment by parth-elastic** [comment]
@danajuratoni We've uploaded both the discovery docs in Elastic GDrive.
Please find it here for [SharePoint Server](https://docs.google.com/document/d/1w4TnzVMvk7yNUUpyFRHut97LheTiCobVg59UHEc1PRQ/edit?usp=drive_link) & [Outlook](https://docs.google.com/document/d/1dX793mbNm7C0KF439wU3saQN1QrSnnWr8oOgZp2tPdE/edit?usp=drive_link)

**Comment by akanshi-elastic** [comment]
@leemthompo Some changes required in SharePoint Server documentation:

Configuration:

use_document_level_security
Toggle to enable [document level security (DLS)](https://www.elastic.co/guide/en/enterprise-search/current/dls.html). When
enabled, full syncs will fetch access control lists for each document and store them in the _allow_access_control field. Access
control syncs fetch users' access control lists and store them in a separate index.


fetch_unique_list_permissions

Toggle to enable  fetch unique list permissions. When disabled this will inherit permissions from its parent site else  unique permission for list will be index. This setting can increase the sync time when enabled

fetch_unique_list_item_permissions

Toggle to enable  fetch unique list item permissions. When disabled this will inherit permissions from its parent site else  unique permission for list item will be index. This setting can increase the sync time when enabled
Can you please make these changes in the documentation?

**Comment by parthpuri-elastic** [comment]
@leemthompo, Documentation for Outlook DLS:

### Setting up the Outlook connector

See the [Developer guide](../../docs/DEVELOPING.md) for setting up connectors.

## Document level security

Document level security (DLS) enables you to restrict access to documents based on user permissions.

Refer to [document level security](https://www.elastic.co/guide/en/enterprise-search/master/dls.html) for more information.

**Note:** Refer to [DLS in Search Applications](https://www.elastic.co/guide/en/enterprise-search/master/dls-e2e-guide.html) to learn how to ingest data from Outlook with DLS enabled, when building a search application.

#### Additional Configuration

##### `Enable document level security`

Toggle to enable [document level security (DLS)](https://www.elastic.co/guide/en/enterprise-search/master/dls.html). When enabled:
- Full syncs will fetch access control lists for each document and store them in the `_allow_access_control` field.
- Access control syncs will fetch users' access control lists and store them in a separate index.

**Comment by parth-elastic** [comment]
@danajuratoni Functional Test has been performed and we have uploaded performance report in Elastic GDrive for both [SharePoint Server](https://docs.google.com/document/d/1x8_Izq-ZORUsxH7jZsoz2P7sHFn0k3W12cQBCr96IxQ/edit?usp=sharing) & [Outlook](https://docs.google.com/document/d/18SnpMiKj6L4bZwA5f8cnzJly-iAkYL6dEUtWDgiFGww/edit?usp=sharing) .

Please verify the same and we are good to close this issue

**Comment by danajuratoni** [comment]
Closing as complete, further fixes to be done as followup.
